### ISSUE TITLE
socket objects should return None for nonblocking reads/writes that would block

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython-esp32#103]
Per existing µPy implementations of `usocket` (e.g. unix port), and the CPython implementation of sockets, Socket read/write should return `None` if the call would block, if the socket is set to nonblocking.

Currently, it returns an empty `bytes` object.

Will submit PR soon.

**Comment by MrSurly** [comment]
PR https://github.com/micropython/micropython-esp32/pull/105

**Comment by MrSurly** [comment]
New PR; I borked the old one.

**Comment by dpgeorge** [comment]
Now fixed; see PR above.
