### ISSUE TITLE
nghttp2_*: No such file or directory

### ISSUE THREAD

**Issue by pacmac** [micropython/micropython-esp32#111]
Just did a clean clone of the current version and the make results in:

	.....
	CC /nfs/qnap/data/uPython/esp32/build/esp-idf/components/wpa_supplicant/src/crypto/crypto_internal-modexp.c
	CC /nfs/qnap/data/uPython/esp32/build/esp-idf/components/wpa_supplicant/src/crypto/crypto_internal-cipher.c
	CC /nfs/qnap/data/uPython/esp32/build/esp-idf/components/wpa_supplicant/port/os_xtensa.c
	LINK build/application.elf
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_http.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_version.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_mem.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_hd_huffman.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_rcbuf.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_callbacks.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_session.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_stream.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_hd.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_priority_spec.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_buf.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_option.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_npn.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_helper.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_frame.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_outbound_item.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_hd_huffman_data.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_pq.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_queue.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_submit.o: No such file or directory
	xtensa-esp32-elf-ld: cannot find /build/esp-idf/components/nghttp/library/nghttp2_map.o: No such file or directory
	make: *** [Makefile:606: build/application.elf] Error 1

Looks like it is not part of the submodules:

	@@ Updating micropython-esp32 (master) ...
	Already up-to-date.
	Branch master set up to track remote branch master from origin.
	Switched to a new branch 'master'
	Submodule 'lib/axtls' (https://github.com/pfalcon/axtls) registered for path 'lib/axtls'
	Submodule 'lib/berkeley-db-1.xx' (https://github.com/pfalcon/berkeley-db-1.xx) registered for path 'lib/berkeley-db-1.xx'
	Submodule 'lib/libffi' (https://github.com/atgreen/libffi) registered for path 'lib/libffi'
	Submodule 'lib/lwip' (http://git.savannah.gnu.org/r/lwip.git) registered for path 'lib/lwip'
	Cloning into '/build/micropython-esp32/lib/axtls'...
	Cloning into '/build/micropython-esp32/lib/berkeley-db-1.xx'...
	Cloning into '/build/micropython-esp32/lib/libffi'...
	Cloning into '/build/micropython-esp32/lib/lwip'...
	Submodule path 'lib/axtls': checked out '67d27df4b5d097e146599fc4fb160a2adcbf5632'
	Submodule path 'lib/berkeley-db-1.xx': checked out 'dab957dacddcbf6cbc85d42df62e189e4877bb72'
	Submodule path 'lib/libffi': checked out 'e9de7e35f2339598b16cbb375f9992643ed81209'
	Submodule path 'lib/lwip': checked out '5b8b5d459e7dd890724515bbfad86c705234f9ec'

**Comment by dpgeorge** [comment]
Did you do "git submodule update --init" in the IDF directory?

**Comment by dpgeorge** [comment]
Assuming fixed.
