### ISSUE TITLE
Cannot flash_erase

### ISSUE THREAD

**Issue by LupascuAndrei** [micropython/micropython-esp32#139]
Using the following code:
```python 
from esp import * 
def test(st, end):
  for i in range(st, end, 4096):
    try:
      flash_erase(i)
      print('working for ' + str(i))
    except:
      print('not working for ' + str(i))
test(0, 0x400000)
```

I can see that only a small amount of sectors ( < 5 ) can be erased from the whole flash memory.
I'm new to micropython-esp32, is this an intended flash protection? If so, is there a straightforward way to disable it?
Thank you.

**Comment by dpgeorge** [comment]
The `esp.flash_erase()` function takes an argument which is the *sector number*, not the address.
