### ISSUE TITLE
mpy-esp32 can not work well 

### ISSUE THREAD

**Issue by ouki-wang** [micropython/micropython-esp32#14]
ESPIDF commit id:8615dbd486ef123876662a5664b3527a24daa92e
MicroPython-ESP32 commit id:864d52764a247d9f9785614a667298dd91bfd2f3   branch esp32

Compile the project.    generate  application.bin
burn application.bin

run the firmware
   >a=3
   >print(a)
   3
   >import os
   what?
   >import sys
   what?
   >
Can someone help me?

**Comment by dpgeorge** [comment]
Try erasing the entire flash first, then make sure you deploy all 3 .bin files: bootloader.bin, partitions.bin and application.bin.

Use `make erase` and `make deploy` to do these steps.

**Comment by nickzoic** [comment]
closing this one, too ... think we cleared it up sufficiently.
