### ISSUE TITLE
Rig

### ISSUE THREAD

**Issue by DVSUHZ-g** [micropython/micropython-esp32#143]
I'm making an augmented reality headset and have been doing research for +8months (lost 90% of it a week ago). 

The rough sketch is this:
![img_20170728_140533](https://user-images.githubusercontent.com/4581103/28730628-f1562330-739e-11e7-8ac8-bf3ceeebbc78.jpg)

Eventually working toward using these respos extensively:
![screenshot_20170728-142610](https://user-images.githubusercontent.com/4581103/28731156-cb4f5452-73a0-11e7-870d-3e0c08a20ee6.png)

Feedback welcome.

**Comment by MrSurly** [comment]
Hi @DVSUHZ-g,

Are you having any specific problems with MicroPython?  Issues are usually places to post a problem with the code, or perhaps a proposed change.

**Comment by DVSUHZ-g** [comment]
As stated in:
https://youtu.be/-MrqCmq3Z5k
*Oi! I wish it could do this.*

**Comment by dpgeorge** [comment]
To discuss your project and get some possible feedback please visit https://forum.micropython.org
