### ISSUE TITLE
Adding Neopixel support

### ISSUE THREAD

**Issue by ghost** [micropython/micropython-esp32#15]
Opening this issue so I can commit and open a PR against it - the LCA2017 open hardware kit has an esp32 and neopixels. Now they work together in shiny harmony.

Actually, the LEDs are APA106, but other than the RGB/GRB order, the apa106 seems to work with stock ws2812 code.

**Comment by mattytrentini** [comment]
Didn't you add Neopixel support to Micropython for the ESP32 in PR #17? (Thanks by the way!) Can this issue be closed then?

**Comment by dpgeorge** [comment]
Yes it's been added!
