### ISSUE TITLE
got error when make: No rule to make target `lib/berkeley-db-1.xx/btree/bt_close.c'

### ISSUE THREAD

**Issue by jszsj** [micropython/micropython-esp32#160]
When I try to build, there's an error:

make: *** No rule to make target `lib/berkeley-db-1.xx/btree/bt_close.c', needed by `build/genhdr/qstr.i.last'.  Stop.

How to solve this issue? Thank you very much!

**Comment by robert-hh** [comment]
No problem here. be sure to run before
`git submodule update --init`
and then start over with:
```
make clean
make
```

**Comment by jszsj** [comment]
That's the key,I forgot that, Thanks!
