### ISSUE TITLE
How can I use webrepl on esp32

### ISSUE THREAD

**Issue by biaoxiaoduan** [micropython/micropython-esp32#169]
I tried to use web repl on esp32, but I found that ESP32 does not have uos.dupterm method, which is implemented with api system_os_post on ESP8266. Is there anyone who use web repl on esp32 successfully?

**Comment by MrSurly** [comment]
See #107

**Comment by nickzoic** [comment]
I'm going to close this one as a duplicate of #107 ... its definitely something we want to implement though!
Thanks for your feedback.
