### ISSUE TITLE
Mesh Network

### ISSUE THREAD

**Issue by pedrofelipest** [micropython/micropython-esp32#176]
How to create mesh network? Has it been implemented?

**Comment by MrSurly** [comment]
For MicroPython ESP32? No.   Probably not anytime soon.

**Comment by nickzoic** [comment]
I went and created this issue for ESP-IDF to add 802.11 Ad-Hoc Networks, but I wouldn't hold your breath.
https://github.com/espressif/esp-idf/issues/989

**Comment by nickzoic** [comment]
@pedrofelipest ESP-NOW protocol might also be of interest to you.
I'm currently working on getting that implemented for MicroPython.

https://github.com/espressif/esp-idf/blob/master/docs/api-reference/wifi/esp_now.rst

**Comment by pedrofelipest** [comment]
Thanks @nickzoic, I will check this implementation.

**Comment by nickzoic** [comment]
(FYI: Espressif aren't likely to support WiFi AdHoc but have other things on the go, including WiFi Direct and ESP-Mesh.  I've closed the issue above.)

**Comment by pedrofelipest** [comment]
@nickovs the ESP-NOW do you have a maximum amount of devices on the network that is mounted?

**Comment by 60999** [comment]
Is there any update progress?
