### ISSUE TITLE
import ssd1306 syntax

### ISSUE THREAD

**Issue by rdagger** [micropython/micropython-esp32#207]
It looks like the daily firmware build doesn't include: 
_micropython-esp32/drivers/display/ssd1306.py_
Or am I using the wrong import syntax?  `import ssd1306`

The library works if I copy ssd1306.py to the ESP32.

**Comment by dpgeorge** [comment]
You are correct: ssd1306.py is not included in the builds.  Not everyone needs this library so it's kept out of the main firmware.  You can easily copy it to the filesystem (or even a pre-compiled version using mpy-cross) when needed.
