### ISSUE TITLE
cannot create makefile under the esp32

### ISSUE THREAD

**Issue by ghost** [micropython/micropython-esp32#21]
Hello,

I could not create `makefile` under the esp32 directory, it seems the system is not case sensitive. Is there an alternative way for the custom `makefile`?

Thanks!

**Comment by dpgeorge** [comment]
> Is there an alternative way for the custom makefile?

You can try "GNUmakefile", that should also override the existing "Makefile".

Otherwise, use "make -f MyMakefile" to specify your makefile explicitly.

**Comment by ghost** [comment]
yes, GNUmakefile works great for me, Thanks!

**Comment by dpgeorge** [comment]
Great.  I added a point about this to the README in f7692bc9a4a55d165fae7494f93fb74b4608715b.
