### ISSUE TITLE
Add support to ure for named-groups

### ISSUE THREAD

**Issue by abencomo** [micropython/micropython-esp32#215]
Will it be possible to add support for named-groups in the ure api?  It will help a lot with the parsing of dynamic URIs and URLs containing named gapturing groups.

https://docs.python.org/3/howto/regex.html#non-capturing-and-named-groups

**Comment by nickzoic** [comment]
G'day!  This would be a change to `extmod/modure.c` so it'd have to happen in the main micropython repo ...
https://github.com/micropython/micropython ...  

I agree they're a lot nicer to deal in some circumstances with but it might be that they'd make the re implementation a bit heavier than is desired on small platforms ...

**Comment by abencomo** [comment]
Closing this one and opening a new one against the main repo as nickzoic pointed out.

https://github.com/micropython/micropython/issues/3403
