### ISSUE TITLE
is there any support of coap protocol?

### ISSUE THREAD

**Issue by JonathanStrangeHelium** [micropython/micropython-esp32#219]
is there any support of coap protocol?

**Comment by eflukx** [comment]
I see coap protocol is supported in the esp-idf, but probably this could be relatively easily wrapped in Micropython. However, the idf code uses (a submodle) libcoap. Libcoap is GPL licensed, probably this can not be united with Micropython's MIT license.

**Comment by dpgeorge** [comment]
Ideally, support for CoAP would be done in a port-independent way.  This should be discussed upstream.
