### ISSUE TITLE
Toolchain setup in ports/esp32/README is out of date

### ISSUE THREAD

**Issue by aykevl** [micropython/micropython-esp32#237]
The README for the esp32 gives this text as part of "Setting up the toolchain and ESP-IDF":

> Follow the guide "Setting Up ESP-IDF", for Windows, Mac or Linux. You only need to perform up to "Step 2" of the guide, by which stage you should have installed the cross-compile and cloned the ESP-IDF repository.

Apparently they expect the guide to cover cloning of the repository, but it only gives instructions for how to download a binary toolchain from Espressif. I worked around it by also downloading the esp-idf repository, checking out the right hash and doing a submodule update (without compiling), but I'm not sure whether this is the correct approach. Now I have set `ESPIDF` to the esp-idf repository and have added the binary toolchain from Espressif to my `PATH` variable. This works, mostly.

**Comment by dpgeorge** [comment]
The README was improved upstream in commit https://github.com/micropython/micropython/commit/f16c775a0782961a841f77cc48a789b3246d7ef7
