### ISSUE TITLE
Missing machine.enable_irq() etc . .

### ISSUE THREAD

**Issue by annejan** [micropython/micropython-esp32#24]
Unfortunately micropython-esp32 is missing hardware interrupt routine handling functionality. 

Missing `machine.enable_irq()`, `machine.disable_irq()` and `Pin.irq()` methods.

**Comment by dpgeorge** [comment]
Yes it is!  These will be added soon enough.  (See #17 for code that can be used to implement enable/disable irq.)

**Comment by nickzoic** [comment]
Yeah, it's very high on my list right now ... I'd started on it as part
of #23 but decided to split it out into its own thing.
Thanks for putting it on the list!  



-----N





On Mon, Feb 20, 2017, at 15:17, Damien George wrote:

> Yes it is!  These will be added soon enough.  (See #17[1] for code
> that can be used to implement enable/disable irq.)
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
> 



--

Nick Moore <nick@zoic.org> 0409 656 267




Links:

  1. https://github.com/micropython/micropython-esp32/pull/17
  2. https://github.com/micropython/micropython-esp32/issues/24#issuecomment-280984509

**Comment by MrSurly** [comment]
Both #17 and #23 are marked as closed -- is this issue still needed?

**Comment by dpgeorge** [comment]
machine.enable_irq(), machine.disable_irq() and Pin.irq() methods are now all implemented

**Comment by ril3y** [comment]
I see this as closed but I cannot seem to find any documentation on using a TouchPad with an IRQ vs polling.  Am I missing something obvious?

**Comment by MrSurly** [comment]
This repo is deprecated ESP32 code was pulled into mainline quite some time ago.  [Docs for Pin](http://docs.micropython.org/en/v1.9.3/wipy/library/machine.Pin.html)
