### ISSUE TITLE
How to connect to an ESP32 from a mobile application?

### ISSUE THREAD

**Issue by ShrikantKumbhar** [micropython/micropython-esp32#242]
I want to communicate with an ESP32 from my mobile app. Ihave the following micropython code:
import network
ap = network.WLAN(network.AP_IF)
ap.active(True)
ap.config(essid='ESP32')
ap.config(authmode=3, password='123456789')

In this code the access point is created and it is visible in my Android mobile. 
But when  connect my mobile to the access point it is showing the “saved” message instead of “connected” even though I have entered the correct password.
I followed the same procedure using Arduino code and I was able to connect my mobile with the access point created bythe ESP32. Any help is highly appreciated

**Comment by dpgeorge** [comment]
This was asked at https://github.com/micropython/micropython/issues/3518 where the discussion continues.
