### ISSUE TITLE
esp-wrover i2c hardware support

### ISSUE THREAD

**Issue by jonhp** [micropython/micropython-esp32#243]
hi, i am new here, so if this misses the mark in some way, it is not my intent.
it appears that the esp32-wrover module has full hardware support for i2c.
best i can tell, the micropython implementation of i2c is all in code with 
delays for the clocking.
is there a plan to provide support for the native i2c hardware in micropython?

**Comment by Avi-TelnT** [comment]
I believe that ...ports/stm32/machine_i2c.c is HW implemented. and I2C.C with DMA code. 
I see that there is some old CC3000 software code too.  
Search for I2C to see all
https://github.com/micropython/micropython-esp32/blob/046d15f074398cc2968fc66ae2fd25dc31100109/docs/library/machine.I2C.rst

**Comment by MrSurly** [comment]
This repo has been merged into `micropython/micropython`; issues and PRs for ESP32 (or any other platform) should be posted there.

@jonhp You are correct, software I2C right now

@Avi-TelnT That's for the STM32 port

**Comment by Avi-TelnT** [comment]
@MrSurly
And what about ESP32? 
HW or SW?

**Comment by MrSurly** [comment]
@Avi-TelnT Software, right now.  A PR would be welcome, I'm sure.
