### ISSUE TITLE
NodeMCU ESP32 Failed: rst:0x10 RTCWDT_RTC_RESET

### ISSUE THREAD

**Issue by KISSMonX** [micropython/micropython-esp32#247]
```

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 

````

**Comment by KISSMonX** [comment]
**uPyCraft V0.29 firmware works fine.**

but, [https://micropython.org/download#esp32](https://micropython.org/download#esp32) cannot work.

Always rst: 0x10(RTCWDT_RTC_RESET)

**Comment by dpgeorge** [comment]
This repository is no longer used, the code has been merged into https://github.com/micropython/micropython

**Comment by MrSurly** [comment]
@dpgeorge Too bad you can't just turn off _new_ issues.

**Comment by MrSurly** [comment]
Or maybe modify `README.md` with a big notice about it being moved -- I know there's one there now, but move all the other content of the current readme into another file, and just have a link to that from the main readme that only states "this is old..."

**Comment by nickzoic** [comment]
Yeah, I added a notice to the README but I'd agree that we could move
the old README.md to README-OLD.md and make a new one which is just a
big stop sign :-)
Or we can archive this whole repo I suppose, although I'd better pull my
finger out and copy the open PRs and stuff across.
-----N

**Comment by dpgeorge** [comment]
Ok, I updated the main description of the repo to point to upstream, and added ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md to also give a notice when new issue/PRs are opened.  Hopefully that helps!

**Comment by MrSurly** [comment]
> Ok, I updated the main description of the repo to point to upstream

git push?

Edit: Ah, main description, not the README.md.
