### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [micropython/micropython-esp32#25]
Hi there,
I'm working with Micropython on the ESP8266, the [WeMos board](https://www.wemos.cc/product/d1-mini.html).

I'm experiencing some issues where the code in `main.py` fails while the same, when run in the micropython shell works ok.

This got me thinking about how to approach these kinds of problems.
How do you approach them when developing?
Do you have and esp board connected to a JTAG?

**Comment by nickzoic** [comment]
Ha, not right now.  My plan is to get a relatively low-tech bunch of boards hanging off a spare rPi and run that as a CI kind of setup.  But that hasn't happened yet ... I got distracted by trying to put together some RF screening for it.

But if your immediate problem is with ESP8266 code, you'd be better off posting an issue (with examples) over in the *main* micropython project at https://github.com/micropython/micropython/issues/ ... this project is just a temporary fork specific to ESP32.
