### ISSUE TITLE
UPload to ESP32 board

### ISSUE THREAD

**Issue by armon75226** [micropython/micropython-esp32#250]
I am having a hard time uploading file to my ESP32 via Com port.
It is more like hit or miss.  for instance, I  update my file (test.py) on PC and using shell command to connect to the port and upload: ampy --port COM4 --baud 115200 put test.py
Upon submitting the file I have to hold down Boot bottom to be able to copy the file to my board.   But it works sometimes and sometimes it wont.  very frustrating.  I changed the time sleep to 4 second in pyboard.py  but no luck. 

Has anyone come a cross this issue and fixed it?
Thanks

**Comment by robert-hh** [comment]
This is not an issue, just an inconsistency between ampy and MP. You asked this question on the forum too, which is the proper place.
