### ISSUE TITLE
How can I use WPA2-Enterprise on ESP32?

### ISSUE THREAD

**Issue by Nyarn-WTF** [micropython/micropython-esp32#255]
I want to use WPA2-Enterprise on ESP32.
I tried coding with reference to the 8266 example, but failed because "WLAN.STA" was not found. How can I do it?

"""
from network import WLAN
wlan = WLAN(mode = WLAN.STA)
wlan.connect(ssid = "SSID",auth = (WLAN.WPA2_ENT,"ID","PW"),identity = "identity")
"""

**Comment by dpgeorge** [comment]
Enterprise is not currently supported on ethier esp8266 or esp32.

The main repository for MicroPython on esp32 is now at https://github.com/micropython/micropython

**Comment by Nyarn-WTF** [comment]
Thank you!
Then I will ask the question from there next time.
