### ISSUE TITLE
ESP32 micropython  Compilation error！！

### ISSUE THREAD

**Issue by MRxing1** [micropython/micropython-esp32#262]
CC extmod/mpexception.c
CC ../../lib/oofatfs/ff.c
CC ../../lib/oofatfs/ffunicode.c
CC ../../lib/littlefs/lfs2.c
CC ../../lib/littlefs/lfs2_util.c
CC ../../extmod/modbtree.c
In file included from ../../lib/berkeley-db-1.xx/PORT/include/../../btree/btree.h:44:0,
                 from ../../extmod/modbtree.c:38:
../../lib/berkeley-db-1.xx/PORT/include/mpool.h:50:2: error: expected specifier-qualifier-list before 'CIRCLEQ_ENTRY'
  CIRCLEQ_ENTRY(_bkt) hq;  /* hash queue */
  ^
../../lib/berkeley-db-1.xx/PORT/include/mpool.h:61:2: error: expected specifier-qualifier-list before 'CIRCLEQ_HEAD'
  CIRCLEQ_HEAD(_lqh, _bkt) lqh; /* lru queue head */
  ^
../../extmod/modbtree.c:329:14: error: unknown type name 'FILEVTABLE'
 STATIC const FILEVTABLE btree_stream_fvtable = {
              ^
../../extmod/modbtree.c:330:5: error: initialization makes integer from pointer without a cast [-Werror=int-conversion]
     mp_stream_posix_read,
     ^
../../extmod/modbtree.c:330:5: note: (near initialization for 'btree_stream_fvtable')
../../extmod/modbtree.c:331:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_write,
     ^
../../extmod/modbtree.c:331:5: note: (near initialization for 'btree_stream_fvtable')
../../extmod/modbtree.c:332:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_lseek,
     ^
../../extmod/modbtree.c:332:5: note: (near initialization for 'btree_stream_fvtable')
../../extmod/modbtree.c:333:5: error: excess elements in scalar initializer [-Werror]
     mp_stream_posix_fsync
     ^
../../extmod/modbtree.c:333:5: note: (near initialization for 'btree_stream_fvtable')
../../extmod/modbtree.c: In function 'mod_btree_open':
../../extmod/modbtree.c:362:52: error: passing argument 2 of '__bt_open' makes integer from pointer without a cast [-Werror=int-conversion]
     DB *db = __bt_open(MP_OBJ_TO_PTR(pos_args[0]), &btree_stream_fvtable, &open
                                                    ^
In file included from ../../extmod/modbtree.c:37:0:
../../lib/berkeley-db-1.xx/PORT/include/db.h:230:5: note: expected 'int' but argument is of type 'const int *'
 DB *__bt_open __P((const char *, int, int, const BTREEINFO *, int));
     ^
../../extmod/modbtree.c:362:75: error: passing argument 3 of '__bt_open' makes integer from pointer without a cast [-Werror=int-conversion]
  *db = __bt_open(MP_OBJ_TO_PTR(pos_args[0]), &btree_stream_fvtable, &openinfo, 
                                                                     ^
In file included from ../../extmod/modbtree.c:37:0:
../../lib/berkeley-db-1.xx/PORT/include/db.h:230:5: note: expected 'int' but argument is of type 'BTREEINFO * {aka struct <anonymous> *}'
 DB *__bt_open __P((const char *, int, int, const BTREEINFO *, int));
     ^
../../extmod/modbtree.c:362:14: error: too few arguments to function '__bt_open'
     DB *db = __bt_open(MP_OBJ_TO_PTR(pos_args[0]), &btree_stream_fvtable, &open
              ^
In file included from ../../extmod/modbtree.c:37:0:
../../lib/berkeley-db-1.xx/PORT/include/db.h:230:5: note: declared here
 DB *__bt_open __P((const char *, int, int, const BTREEINFO *, int));
     ^
cc1: all warnings being treated as errors
../../py/mkrules.mk:63: recipe for target 'build-GENERIC_SPIRAM/extmod/modbtree.o' failed
make: *** [build-GENERIC_SPIRAM/extmod/modbtree.o] Error 1

micropytho Compilation error!
1   lib/berkeley-db-1.xx library file I have loaded and updated.
![image](https://user-images.githubusercontent.com/43816056/114650506-f2012480-9d14-11eb-80a1-fa7f51d77112.png)
2  The following commands have been executed：
xkp@xkp-VirtualBox:~/esp32/micropython$ git submodule init lib/berkeley-db-1.xx
xkp@xkp-VirtualBox:~/esp32/micropython$ git submodule update
子模组路径 'lib/berkeley-db-1.xx'：检出 '7b31cae3c0892a7fca2089cb0354a4920c98c413'

The result is still not good!

Hope to get your reply!

Best wishes!

**Comment by dpgeorge** [comment]
Please do not use this repository for reporting issues.  Please use https://github.com/micropython/micropython
