### ISSUE TITLE
Compile Latest Fails

### ISSUE THREAD

**Issue by diginfo** [micropython/micropython-esp32#46]
I just tried compiling the latest and it fails as follows:

	......
	.....
	.....
	CC /Users/pac/esp/esp-idf/components/wpa_supplicant/src/crypto/crypto_internal-cipher.c
	CC /Users/pac/esp/esp-idf/components/wpa_supplicant/port/os_xtensa.c
	LINK build/application.elf
	build//Users/pac/esp/esp-idf/components/esp32/phy_init.o:(.literal.esp_phy_rf_deinit+0x8): undefined reference to `phy_close_rf'
	build//Users/pac/esp/esp-idf/components/esp32/phy_init.o: In function `esp_phy_rf_deinit':
	phy_init.c:(.text.esp_phy_rf_deinit+0x2f): undefined reference to `phy_close_rf'
	make: *** [build/application.elf] Error 1

Here's the step-by-step:

	## Downgrade ESP-IDF Version
	cd ~/esp/esp-idf
	sudo git pull
	sudo git checkout c06cc31d85cc700e1dbddbe527d4282c4bc5845a
	
	## Clone ESP-32 Micropython
	cd ~/esp
	rm -rf micropython-esp32 
	git clone https://github.com/micropython/micropython-esp32.git
	
	## Create GNUmakefile
	nano ~/esp/micropython-esp32/esp32/GNUmakefile
	
	ESPIDF=/Users/pac/esp/esp-idf
	PORT=/dev/tty.usbserial-DQ008YJN
	FLASH_MODE=qio
	FLASH_SIZE=4MB
	
	include Makefile
	
	## Pre-Compile in Root
	cd ~/esp/micropython-esp32
	make -C mpy-cross
	
	## BUILD
	cd ~/esp/micropython-esp32/esp32
	make

**Comment by dpgeorge** [comment]
When you downgrade the ESP IDF you need to do `git submodule update --init`.

**Comment by diginfo** [comment]
OOps, yes that works, I have added that step to my procedure and won't make the same mistake again.

Thanks so much

**Comment by zmijunkie** [comment]
Happy to have seen this issue - and it's solution. REPL Fun started a few minutes later ;-)
