### ISSUE TITLE
SD card support

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython-esp32#55]
Doesn't appear SD/MMC support exists yet?

**Comment by dpgeorge** [comment]
Not the hardware driver.  But the standard software one (written in Python) should work, it can be found at drivers/sdcard/sdcard.py.

**Comment by MrSurly** [comment]
Implemented using bit-banged SPI in `extmod`, I see.   Any desire for "native" SPI & SDcard?

**Comment by MrSurly** [comment]
Leaving for later
