### ISSUE TITLE
sockets don't support ioctl

### ISSUE THREAD

**Issue by dpgeorge** [micropython/micropython-esp32#6]
socket objects should support (C-level) ioctl method.  The easiest way (?) to implement it is using lwip_select to poll for read/write/error on a given socket.

**Comment by nickzoic** [comment]
Okay, I implemented this in feature/6-support-ioctl using lwip_select but it doesn't seem reliable, more debugging needed ... sockets with nothing to read still come back as readable.  Might try another approach as well ...

**Comment by nickzoic** [comment]
See 0ab7e96cae362743c0a15bf3716616a261fa2f9c

**Comment by dpgeorge** [comment]
ioctl should be working well now for sockets.
