### ISSUE TITLE
 cannot find -lrtc_pm

### ISSUE THREAD

**Issue by kimyong** [micropython/micropython-esp32#61]
Hi I was able to build the image until today. Seems like I am missing the rtc_pm library. May I know where is this library located?

LINK build/application.elf
xtensa-esp32-elf-ld: cannot find -lrtc_pm
Makefile:586: recipe for target 'build/ap
make: *** [build/application.elf] Error 1

**Comment by dpgeorge** [comment]
Go to the ESP IDF directory and do `git pull` followed by `git submodule update --init`
