### ISSUE TITLE
Proposed code styling via Astyle

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython-esp32#65]
For a PR #64 , I used `astyle -KSUHp -s4`.  Propose adding a single sentence to `CODECONVENTIONS.md`, recommending it's usage.

**Comment by dpgeorge** [comment]
I've never used astyle.  Is it popular / well known?

**Comment by MrSurly** [comment]
Well known among the developers I know =)  Available for Linux, Mac, Windows.  In most Linux repos, and installable on Mac easily via Brew.  Just thought this is one of those thing's that's easy to automate, or make easy for others.

There's also [indent](https://www.gnu.org/software/indent/).

**Comment by nickzoic** [comment]
No objection to using astyle as we go along, it likes whitespace more than I do but at least it leaves most everything else alone.

**Comment by dpgeorge** [comment]
Please see discussion upstream: https://github.com/micropython/micropython/issues/4223
