### ISSUE TITLE
HW SPI Freezes when changing host controller

### ISSUE THREAD

**Issue by MrSurly** [micropython/micropython-esp32#67]
Just putting this here to document an open issue in the IDF that affects HW SPI:  [spi_device_transmit doesn't return when changing host ID](https://github.com/espressif/esp-idf/issues/477).

**Comment by whatnick** [comment]
Interested in this issue as I often have multiple SPI devices on the bus with different SPI modes (and sometimes clock speeds). If it is an IDF issue there will be no fix here for a bit.

**Comment by MrSurly** [comment]
Evidently, this has been fixed "some time ago," per Espressif.
