### ISSUE TITLE
Seems boot.py has not been successfully created

### ISSUE THREAD

**Issue by YanMinge** [micropython/micropython-esp32#72]
I have previously submitted an issue [#59](https://github.com/micropython/micropython-esp32/issues/59),
and I have done some work on vfs_fat and oofatfs, now I can use C language to create, modify, or delete files. but still some information I want to confirm with you.

I tried to modify the boot.py in micropython-esp32\esp32\modules\inisetup.py. But it looks like it can not work.
```
def setup():
    check_bootsec()
    print("Performing initial setup")
    uos.VfsFat.mkfs(bdev)
    vfs = uos.VfsFat(bdev)
    uos.mount(vfs, '/flash')
    uos.chdir('/flash')
    with open("boot.py", "w") as f:
        f.write("import Undefined")
    with open("main.py", "w") as f2:
        f2.write("import Undefined2")
    return vfs
```
It expect to have the following log after startup, But it seems there have no boot.py been executed.
```
Traceback (most recent call last):
  File "boot.py", line 3, in <module>
ImportError: no module named 'Undefined'
```
Have you tested the implementation of boot.py or main.py with python?

**Comment by dpgeorge** [comment]
I'm not quite sure what you are asking... but the code you have should work just fine.  main.py and boot.py have been tested and work.

The exception that you get, "ImportError: no module named 'Undefined'" is expected because there is no module called "Undefined", and that's what boot.py is trying to import.

**Comment by dpgeorge** [comment]
To check if boot.py is created just do:
```python
>>> f=open('boot.py')
>>> print(f.read())
>>> f.close()
```

**Comment by YanMinge** [comment]
Yes, as you said, I change the content of boot.py with code in inisetup.py, so if boot.py is executed, I expect to have the log
```
Traceback (most recent call last):
  File "boot.py", line 3, in <module>
ImportError: no module named 'Undefined'
```
But I didn‘t get any error log like this.

**Comment by dpgeorge** [comment]
> I change the boot.py with code in inisetup.py,

inisetup.py is only run if there is no existing filesystem on your board.  To make it execute you'll need to do "make erase" before doing "make deploy".

**Comment by YanMinge** [comment]
Got it, I ignored the contents of _boot.py, sorry to waste your time.
