### ISSUE TITLE
Triggering safe mode

### ISSUE THREAD

**Issue by laurivosandi** [micropython/micropython-esp32#97]
Hi, I've ended up with a sort of bricked ESP32, the boot.py contains code which triggers low level exception causing evental reboot. How can I trigger the safe mode described in MicroPython docs? It seems for ESP32 it hasn't been implemented?

**Comment by dpgeorge** [comment]
Since ESP32 is a module and not a board there is no standard "user button" that can be used to enter safe mode.  They only (and easy) way out is to erase the entire flash, to remove the offending boot.py (eg "make erase").
